[build]
  # This command runs our build script.
  command = "npm install && npm run build"
  
  # This is the directory that Netlify will publish.
  publish = "/"

  # Directory for serverless functions (if you add any in the future).
  functions = "functions"

# Optional: Redirect rule for cleaner function URLs
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
