site_logo: /assets/image_fx-5-.jpg
site_favicon: /assets/image_fx-5-.jpg
site_title: EMIR
site_description: EMIR WEB
primary_color: "#d8b125"
secondary_color: "#ffffff"
social_facebook: "#"
social_instagram: "#"
social_pinterest: "#"
